Refactoring, try to fix compile error
```
:compileJava/home/travis/build/hamstercommunity/hamcrest-auto-matcher/sr
c/main/java/com/github/hamstercommunity/matcher/auto/AutoConfigBuilder.j
ava:96: error: incompatible types: cannot infer type-variable(s) P#1,P#2
			configBuilder.addIterableProperty(propertyName,
createGetter(method), AutoMatcher::equalTo);
			                                 ^
    (argument mismatch; Function<T,P#2> cannot be converted to
Function<T,Iterable<? extends Object>>)
  where P#1,B,P#2,T are type-variables:
    P#1 extends Object declared in method
<P#1>addIterableProperty(String,Function<B,Iterable<? extends
P#1>>,Function<P#1,Matcher<P#1>>)
    B extends Object declared in class Builder
    P#2 extends Object declared in method <P#2>createGetter(Method)
    T extends Object declared in class AutoConfigBuilder
```